#!/bin/ksh
 
set -x

# HOMEfv3 set in qsub job

. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR
. $USHfv3/run_commands_forecast.sh
 
export DATA=${DATA:-${STMP}/tmpnwprd-${CDATE}/${envir}/${job}_${cyc}}
#cltthinkdeb rm -fr $DATA
mkdir -p $DATA
cd $DATA

#cltorg  . /usrx/local/prod/lmod/lmod/init/ksh
#replaced ty two following lines according to Chris at WCOSS help. 


export pid=$$
export pgmout="OUTPUT.${pid}"

# Get my date file; cyc is tm00 date, comes from qsub script
##cp $DATEdir/t${cyc}z ncepdate
##export CYCLE=`cut -c 7-16 ncepdate`
##export PDY=`cut -c 7-14 ncepdate`

# CYCLE and PDY now come from rocoto script
echo "DATEXX${CYCLE}" > ncepdate
export PDYrun=`echo $CDATE | cut -c 1-8`
export CYCrun=`echo $CDATE | cut -c 9-10`

#COMROOT and GESROOT are the same dirs
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDYrun}/${CYCrun}
mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

mkdir -p $COMOUT/guess.${tmmark}
mkdir -p $COMOUT/anl.${tmmark}
export GUESSdir=$COMOUT/guess.${tmmark}
export ensGUESSdir=$COMOUT/ens_guess.${tmmark}
export ANLdir=$COMOUT/anl.${tmmark}
export EnKFANLdir=$COMOUT/enkf_anl.${tmmark}
mkdir -p $EnKFANLdir
export NWGES_ens=${GESROOT}/${NET}/${envir}/${RUN}_ens.${PDY}/${cyc}
mkdir -p $NWGES_ens

CDATE=${CDATE:-${PDY}${cyc}}


if [ $machine = HERA -o $machine = hera ] ; then
#cltthinkdeb are this block needed?
  export UTIL=${UTIL:-$HOMEfv3/util/ush}
  export gsiexec0=/scratch2/NCEPDEV/meso/noscrub/Wanshu.Wu/build/bin/gsi.x
  export fixgsi=$HOMEfv3/sorc/regional_gsi.fd/fix/
  export fixcrtm=${fixcrtm:-/scratch2/NCEPDEV/da/save/Michael.Lueken/nwprod/lib/crtm/2.2.3/fix_update}
fi
if [ $machine = WCOSS ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=/meso/save/$USER/fv3reg_aug2018/fv3gsi_reg/build/bin/gsi.x
  export fixgsi=/meso/save/$USER/fv3reg_aug2018/fv3gsi_reg/ProdGSI/fix
  export fixcrtm=/da/save/Michael.Lueken/CRTM_REL-2.2.3/crtm_v2.2.3/fix_update
fi
if [ $machine = DELL ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=/gpfs/dell2/emc/modeling/noscrub/$USER/fv3reg_oct2018/fv3gfs/sorc/gsi.fd/build/bin/gsi.x
  export fixgsi=/gpfs/dell2/emc/modeling/noscrub/$USER/fv3reg_oct2018/fv3gfs/sorc/gsi.fd/fix
  export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.6/fix
fi




hostname > hname
hl=`cut -c 1-1 hname`

if [ hl = m ] ; then 
  wcoss=tp
fi
if [ hl = m ] ; then 
  wcoss=gp
fi

if [ $machine = hera -o $machine = HERA ] ; then
   export COMINgfs=${COMINgfs:-/scratch2/NCEPDEV/rstprod/com/gfs/prod}
   export COMINnam=/scratch2/NCEPDEV/rstprod/com/nam/prod
   export COMINrap=${COMINrap:-/scratch4/NCEPDEV/rstprod/com/rap/prod}
   COMINrtma=/scratch2/NCEPDEV/rstprod/com/rtma2p5/prod
   # bias correction files from prev cycle
   export COMINbias=$COMOUT
fi
if [ $machine = WCOSS_C -o $machine = WCOSS -o $machine = DELL ] ; then
   COMINgfs=/gpfs/hps/nco/ops/com/gfs/prod
   # This is the FV3GDAS enkf I mirror to dev
#  COMINgfspll=/gpfs/${wcoss}2/ptmp/$USER/prfv3rt1
   COMINgfspll=/gpfs/dell1/nco/ops/com/gfs/para
   COMINnam=/gpfs/${wcoss}2/nco/ops/com/nam/prod
   COMINrap=/gpfs/hps/nco/ops/com/rap/prod
   COMINbias=$COMOUT
   COMINrtma=/gpfs/${wcoss}2/nco/ops/com/rtma/prod
fi







#run script
${HOMEfv3}/scripts/dev-exfv3cam_sar_efcstpost.sh

cat $pgmout
cat stderr

if [ ${RM_TMPDIR:-NO} = YES ] ; then rm -rf $DATA ; fi

date

exit
