#!/bin/ksh
 
set -x
machine=${machine:-DELL}
. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR
. $USHfv3/run_commands_bc.sh
export CHGRESEXEC=$EXECfv3/regional_chgres_cube.x
#cltorg export CHGRESSH=$USHfv3/global_chgres.sh
export CHGRESSH=$USHfv3/dev-global_chgres_driver_dacycle_hourly.sh
export GETGES=$HOMEfv3/util/ush/getges_linkges_hourlypgrb_new.sh
# HOMEdir set in qsub job


export DATA=${DATA:-${STMP}/tmpnwprd-${CDATE}/${envir}/${job}_${cyc}_ens_${ENSGRP:-xx}}
mkdir -p $DATA 
cd  $DATA


export pid=$$
export pgmout="OUTPUT.${pid}"

# CYCLE and PDY now come from rocoto script






##export CYCLE=`cut -c 7-16 ncepdate`
##export PDY=`cut -c 7-14 ncepdate`
offset=`echo $tmmark | cut -c 3-4`
export month=`echo $CDATE | cut -c 5-6`
export day=`echo $CDATE | cut -c 7-8`

export CYCLEguess=`$NDATE -12 $CDATE`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`
export PDYtm12=`echo $CYCLEguess | cut -c 1-8`
export cycguess=`echo $CYCLEguess | cut -c 9-10`

export CYCLEtm06=`$NDATE -06 $CYCLE`
export PDYtm06=`echo $CYCLEtm06 | cut -c 1-8`
export cyctm06=`echo $CYCLEtm06 | cut -c 9-10`
export PDYrun=`echo $CDATE | cut -c 1-8`
export cyc=`echo $CDATE | cut -c 9-10`



##export CYCLE=`cut -c 7-16 ncepdate`
##export PDY=`cut -c 7-14 ncepdate`
export CYCLEguess=`$NDATE -12 $CYCLE`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`




##export CYCLE=`cut -c 7-16 ncepdate`
##export PDY=`cut -c 7-14 ncepdate`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`

if [ $machine = WCOSS_C ]; then
 export KMP_AFFINITY=disabled
 export FIXgsm=/gpfs/hps/emc/global/noscrub/emc.glopara/svn/fv3gfs/fix/fix_am
 export DATA=/gpfs/hps/ptmp/${LOGNAME}/wrk.chgres
 export APRUNC="aprun -n 1 -N 1 -j 1 -d $OMP_NUM_THREADS_CH -cc depth"
 export INIDIR=/gpfs/hps/nco/ops/com/gfs/prod/gfs.$ymd
 export HOMEgfs=$LS_SUBCWD/..
  export UTIL=/scratch2/NCEPDEV/meso/save/$USER/run_it_regional/exec
elif [ $machine = WCOSS ]; then
 export APRUNC="time"
 export INIDIR=/ptmpp2/$USER/prfv3rt1/gfs.$ymd/$hhcyc

  export UTIL=$HOMEfv3/util/ush
#export INIDIR=/gpfs/dell3/ptmp/emc.glopara/ROTDIRS/prfv3rt1/gfs.$ymd/$hhcyc
elif [ $machine = DELL ]; then
#####################################
# Define COM directories
#####################################
export COMINgdas=${COMINgdas:-/gpfs/dell1/nco/ops/com/gfs/prod}
export GBCOMINgfs=${GBCOMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMgfs=${COMgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
 export UTIL=$HOMEfv3/util/ush
 export APRUNC="time"
 export KMP_AFFINITY=disabled
 export INIDIR=${COMgfs}/gfs.$ymd/$hhcyc
 
elif [ $machine = HERA -o $machine = hera ]; then
 export UTIL=$HOMEfv3/util/ush
 export CDUMP=${CDUMP:-gdas}                   # gfs or gdas
 COMROOTp2=/scratch1/NCEPDEV/rstprod/com
 export ymd=`echo $CDATE | cut -c 1-8`
 export INIDIR=$COMgfs/gfs/prod/${CDUMP}.$ymd
 ulimit -a
 ulimit -s unlimited
elif [ $machine = wcoss_cray -o $machine = WCOSS_CRAY ]; then
    export UTIL=$HOMEfv3/util/ush
    export CDUMP=${CDUMP:-gdas}                   # gfs or gdas
    export ymd=`echo $CDATE | cut -c 1-8`
    export INIDIR=$COMgfs/gfs/prod/${CDUMP}.$ymd
    ulimit -a
    ulimit -s unlimited

else
 echo "$machine not supported, exit"
 exit
fi
#

# setup ensemble filelist03

if [ $machine = HERA -o machine = hera  ] ; then
export   COMINgfs=${COMINgfs:-/scratch1/NCEPDEV/rstprod/com/gfs/prod}
export   COMINnam=${COMINnam:-/scratch1/NCEPDEV/rstprod/com/nam/prod}
export   COMINrtma=${COMINrtma:-/scratch2/NCEPDEV/rstprod/com/rtma2p5/prod}
   # bias correction files from prev cycle
export   COMINbias=$COMOUTtm06
fi
if [ $machine = WCOSS_C -o $machine = WCOSS -o $machine = DELL ] ; then
export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
   # This is the FV3GDAS enkf I mirror to dev
#  COMINgfspll=/gpfs/gp2/ptmp/$USER/prfv3rt1
#clt   COMINgfspll=/gpfs/dell1/nco/ops/com/gfs/para
export    COMINnam=/gpfs/${wcoss}2/nco/ops/com/nam/prod
export   COMINrap=/gpfs/hps/nco/ops/com/rap/prod
export   COMINbias=$COMOUTtm06
export   COMINrtma=/gpfs/${wcoss}2/nco/ops/com/rtma/prod
export   MYGDASpll=$COMINgfspll/gdas.${PDYa}/${cya}
export   GBGDASpll=/gpfs/dell1/nco/ops/com/gfs/para/gdas.${PDYa}/${cya}
fi



#COMROOT and GESROOT are the same dirs
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDYrun}/${cyc}
mkdir -p $COMOUT
#cltorg mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/EXP${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

#mkdir -p $COMOUT/gfsanl.tm12
#cltorg export INPdir=$COMOUT/gfsanl.tm12
export ensINPdir=$GESROOT/${RUN}/EXP${envir}/ens${RUN}.${PDYrun}/${cyc}/dirLBC/$tmmark
if [ $tmmark = tm12 ] || [  $tmmark = tm06 -a ${l_coldstart_anal:-FALSE}  = TRUE ]  ; then    # SAR-DA
  export INPdir=$COMOUT/gfsanl.$tmmark
else
  export INPdir=${COMOUT}/anl.${dom:+${dom}.}${tmmark}
fi
mkdir -p $ensINPdir
#
#run script
#${SCRIPTdir}/exfv3sar_chgres_ens_firstguess.sh
${HOMEfv3}/scripts/dev-exfv3cam_sar_chgres_ens_fcstbndy.sh

#cltorg if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
