#!/bin/ksh
 
set -x

# HOMEfv3 set in qsub job

. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR
. $USHfv3/run_commands_bc.sh

####################################
# Specify Execution Areas
####################################
#cltorg export CHGRESEXEC=$EXECfv3/regional_chgres.x
export CHGRESEXEC=$EXECfv3/regional_chgres_cube.x
#cltorg export CHGRESSH=$USHfv3/global_chgres.sh
export CHGRESSH=$USHfv3/dev-ens-global_chgres_driver.sh
export GETGES=$HOMEfv3/util/ush/getges_linkges_hourlypgrb_new.sh

export DATA=${DATA:-${STMP}/tmpnwprd-${CDATE}/${envir}/${job}_${cyc}_ens_${ENSGRP:-xx}}
mkdir -p $DATA 
cd  $DATA

machine=${machine:-DELL}
# WCOSS environment settings
#####################################
export CDUMP=gfs
export CDAS=gfs
export LEVS=${LEVS:-61}
export LSOIL=4
export REGIONAL=1		# REGIONAL=0 - uniform, stretch, or nest
				# REGIONAL=1 - generate data and boundary (for regional case)
				# REGIONAL=2 - generate boundaries only (for regional case)
export HALO=4
export ictype=pfv3gfs
export nst_anl=.false.		# false or true to include NST analysis
export KMP_AFFINITY=disabled
export NTRAC=7			# output all gfdl mp tracers







export pid=$$
export pgmout="OUTPUT.${pid}"
#some cycle related variables
# CYCLE and PDY now come from rocoto script
echo "DATEXX${CYCLE}" > ncepdate

export month=`echo $CDATE | cut -c 5-6`
export day=`echo $CDATE | cut -c 7-8`

export CYCLEguess=`$NDATE -12 $CDATE`
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`
export PDYtm12=`echo $CYCLEguess | cut -c 1-8`
export cycguess=`echo $CYCLEguess | cut -c 9-10`

export CYCLEtm06=`$NDATE -06 $CYCLE`
export PDYtm06=`echo $CYCLEtm06 | cut -c 1-8`
export cyctm06=`echo $CYCLEtm06 | cut -c 9-10`

export PDY=`echo $CDATE | cut -c 1-8`



##export CYCLE=`cut -c 7-16 ncepdate`
##export PDY=`cut -c 7-14 ncepdate`
export CYCLEguess=`$NDATE -12 $CYCLE`
export CDATE=$CYCLEguess
export ymd=`echo $CDATE | cut -c 1-8`
export hhcyc=`echo $CDATE | cut -c 9-10`

if [ $machine = hera -o $machine = HERA ] ; then
#clthinkdeb are the bloak needed? 
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=/scratch2/NCEPDEV/meso/noscrub/Wanshu.Wu/build/bin/gsi.x
  export fixgsi=$HOMEfv3/sorc/regional_gsi.fd/fix/
  export fixcrtm=${fixcrtm:-/scratch2/NCEPDEV/da/save/Michael.Lueken/nwprod/lib/crtm/2.2.3/fix_update}
elif [ $machine = wcoss_dell_p3 ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec=${EXECfv3}/gsi.x
  export fixgsi=${HOMEfv3}/sorc/gsi.fd/fix
  #export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.6/fix
  export fixcrtm=/usrx/local/nceplibs/dev/NCEPLIBS/src/crtm_v2.3.0/fix
elif [ $machine = wcoss_dell_p3.5 ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=${EXECfv3}/regional_gsi.x
  export fixgsi=/gpfs/dell6/emc/modeling/noscrub/Eric.Rogers/fv3lam_for_dellp3.5/sorc/regional_gsi.fd/fix
  #export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.6/fix
  export fixcrtm=/usrx/local/nceplibs/dev/NCEPLIBS/src/crtm_v2.3.0/fix

elif [ $machine = WCOSS ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=/meso/save/${USER}/fv3reg_aug2018/fv3gsi_reg/build/bin/gsi.x
  export fixgsi=/meso/save/${USER}/fv3reg_aug2018/fv3gsi_reg/ProdGSI/fix
  export fixcrtm=/da/save/Michael.Lueken/CRTM_REL-2.2.3/crtm_v2.2.3/fix_update
elif [ $machine = wcoss_cray ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=${EXECfv3}/regional_gsi.x
  export fixgsi="/gpfs/hps3/emc/meso/save/Eric.Rogers/regional_workflow/regional_gsi.fd/fix"
  export fixcrtm=/gpfs/hps/nco/ops/nwpara/lib/crtm/v2.2.7/fix
  export gsiexec0=/gpfs/hps3/emc/meso/save/Ting.Lei/dr-CAM-new/dr-gsi-mixdual/ProdGSI/exec/global_gsi.x

elif [ $machine = DELL ] ; then
  export UTIL=${HOMEfv3}/util/ush
  export gsiexec0=${EXECfv3}/regional_gsi.x
  export fixgsi=${HOMEfv3}/sorc/regional_gsi.fd/fix
#clt 20200424   export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.6/fix
  export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.7/fix
fi



# this is the 1st job in the cycle so save date file
# for all other J-jobs
#cltold cp ncepdate $DATEdir/t${cyc}z

#COMROOT and GESROOT are the same dirs
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
#cltorg mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/EXP${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

#mkdir -p $COMOUT/gfsanl.tm12
#cltorg export INPdir=$COMOUT/gfsanl.tm12
#cltorg xport INPdir=${COMOUT}/gfsanl.${dom:+${dom}.}${tmmark}
if [ $tmmark = tm12 -o $tmmark = tm06  ] ; then	# SAR-DA
  if [ ${l_coldstart_anal:-TRUE}  = TRUE  ] ; then	# SAR-DA
    export INPdir=$COMOUT/gfsguess.$tmmark
  else
    export INPdir=$COMOUT/gfsanl.$tmmark
  fi
elif [ $tmmark = tm00 ] ; then	# SAR without DA
  export INPdir=$COMOUT/anl.${dom:+${dom}.}$tmmark
fi
export ensINPdir=$GESROOT/${RUN}/EXP${envir}/ens${RUN}.${PDY}/${cyc}/$tmmark
mkdir -p $ensINPdir
#
#run script
${HOMEfv3}/scripts/dev-exfv3cam_sar_make_ic_ens_firstguess.sh

#cltorg if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

exit
