#!/bin/ksh
 
set -x

# HOMEfv3 set in qsub job
machine=${machine:-hera}

. $HOMEfv3/jobs/JFV3CAM_SAR_ENVIR
. $USHfv3/run_commands_forecast.sh
 
export DATATOP=${DATATOP:-${STMP}/tmpnwprd/${envir}/${job}_${cyc}}

#cltorg  . /usrx/local/prod/lmod/lmod/init/ksh
#replaced ty two following lines according to Chris at WCOSS help. 

export pid=$$
export pgmout="OUTPUT.${pid}"

# Get my date file; cyc is tm00 date, comes from qsub script
##cp $DATEdir/t${cyc}z ncepdate
##export CYCLE=`cut -c 7-16 ncepdate`
##export PDY=`cut -c 7-14 ncepdate`

# CYCLE and PDY now come from rocoto script
echo "DATEXX${CYCLE}" > ncepdate

#COMROOT and GESROOT are the same dirs
mkdir -p $COMROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}
export NWGES=$GESROOT/${RUN}/${envir}/${RUN}.${PDY}/${cyc}

mkdir -p $COMOUT/guess.${tmmark}
mkdir -p $COMOUT/anl.${tmmark}
export GUESSdir=$COMOUT/guess.${tmmark}
export ensGUESSdir=$COMOUT/ens_guess.${tmmark}
export ANLdir=$COMOUT/anl.${tmmark}
export EnKFANLdir=$COMOUT/enkf_anl.${tmmark}
export NWGES_ens=${GESROOT}/${NET}/${envir}/${RUN}_ens.${PDY}/${cyc}
mkdir -p $NWGES_ens

CDATE=${CDATE:-${PDY}${cyc}}



# Set path/file for gsi executable

if [ $machine = hera -o $machine = HERA ] ; then
#clthinkdeb are the bloak needed? 
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=/scratch2/NCEPDEV/meso/noscrub/Wanshu.Wu/build/bin/gsi.x
  export fixgsi=$HOMEfv3/sorc/regional_gsi.fd/fix/
  export fixcrtm=${fixcrtm:-/scratch2/NCEPDEV/da/save/Michael.Lueken/nwprod/lib/crtm/2.2.3/fix_update}
elif [ $machine = WCOSS ] ; then
  export UTIL=$HOMEfv3/util/ush
  export gsiexec0=/meso/save/${USER}/fv3reg_aug2018/fv3gsi_reg/build/bin/gsi.x
  export fixgsi=/meso/save/${USER}/fv3reg_aug2018/fv3gsi_reg/ProdGSI/fix
  export fixcrtm=/da/save/Michael.Lueken/CRTM_REL-2.2.3/crtm_v2.2.3/fix_update
elif [ $machine = wcoss_cray ] ; then
  export fixgsi="/gpfs/hps3/emc/meso/save/Eric.Rogers/regional_workflow/regional_gsi.fd/fix"
  export fixcrtm=/gpfs/hps/nco/ops/nwpara/lib/crtm/v2.2.7/fix

elif [ $machine = DELL ] ; then
  export UTIL=${HOMEfv3}/util/ush
  export gsiexec0=${EXECfv3}/regional_gsi.x
  export fixgsi=${HOMEfv3}/sorc/regional_gsi.fd/fix
#clt 20200424   export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.6/fix
  export fixcrtm=/gpfs/dell1/nco/ops/nwprod/lib/crtm/v2.2.7/fix
fi

hostname > hname
hl=`cut -c 1-1 hname`

if [ hl = m ] ; then 
  wcoss=tp
fi
if [ hl = m ] ; then 
  wcoss=gp
fi


if [ $machine = hera ] ; then
   export COMINgfs=${COMINgfs:-/scratch4/NCEPDEV/rstprod/com/gfs/prod}
   export COMINrap=${COMINrap:-/scratch4/NCEPDEV/rstprod/com/rap/prod}
   export COMINrtma=/scratch4/NCEPDEV/rstprod/com/rtma2p5/prod
   # bias correction files from prev cycle
   export COMINbias=$COMOUT
fi
if [ $machine = wcoss_cray -o $machine = wcoss -o $machine = wcoss_dell_p3 ] ; then
   export COMINgfs=${COMINgfs:-/gpfs/dell1/nco/ops/com/gfs/prod}
   export COMINrap=${COMINrap:-/gpfs/hps/nco/ops/com/rap/prod}
   export COMINrtma=/gpfs/dell2/nco/ops/com/rtma/prod
   # bias correction files from prev cycle
   export COMINbias=$COMOUT
fi



#run script
export gsianlsh=${gsianlsh:-${HOMEfv3}/scripts/dev-exfv3cam_sar_gsianl.sh}
${HOMEfv3}/scripts/dev-exfv3cam_sar_enkf_obs.sh

cat $pgmout
pwd 
ls -l stderr
cat stderr

if [ ${RM_TMPDIR:-NO} = YES ] ; then rm -rf $DATATOP ; fi

date

exit
