#!/bin/ksh
set -x

. $HOMEfv3/jobs/JREGIONAL_ENVIR
. $USHfv3/run_commands_forecast.sh

####################################
# SENDCOM - Copy files to /com directory
####################################
export SENDCOM=${SENDCOM:-YES}

####################################
# Specify Execution Areas
####################################
export POSTGPEXEC=${EXECfv3}/regional_post.x
export WGRIB2=${WGRIB2:-${EXECfv3}/wgrib2new}

####################################
# Run setpdy and initialize PDY variables
####################################
# PDY and CDATE are passed in through Rocoto xml
#setpdy.sh
#. ./PDY
export PDY=`echo $CDATE | cut -c 1-8`
export cyc=`echo $CDATE | cut -c 9-10`

#####################################
# Working directories
#####################################
export INPUT_DATA=${INPUT_DATA:-${STMP}/tmpnwprd-${CDATE}/${envir}/forecast_${tmmark}_${dom:+${dom}_}${cyc}}
#export INPUT_DATA=${INPUT_DATA:-/scratch1/NCEPDEV/stmp2/Ting.Lei/tmpnwprd-${CDATE}/${envir}/forecast_${tmmark}_${dom:+${dom}_}${cyc}}
export DATA=${DATA:-${STMP}/tmpnwprd-${CDATE}/${envir}/${job}}
#export DATA=${DATA:-/scratch1/NCEPDEV/stmp2/Ting.Lei/tmpnwprd-${CDATE}/${envir}/${job}}
if [ -d $DATA ]; then
  rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

export pid=$$
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

#####################################
# Define COM directories
#####################################
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $COMOUT
export NWGES=${GESROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}
mkdir -p $NWGES

#####################################
# wcoss environment settings
#####################################
export OMP_NUM_THREADS=1

env

#####################################
# Execute the script.
#${HOMEfv3}/scripts/exregional_post.sh
${HOMEfv3}/scripts/dev-exregional_post.sh
export err=$?
#####################################

if [ -e $pgmerr ] ; then
cat $pgmerr
fi

if [ -e $pgmout ] ; then
cat $pgmout
fi

exit $err
